In [1]:
import pandas as pd
import sys
import os
import numpy as np

# add the project root to the Python path to allow for absolute imports
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
	sys.path.append(project_root)

In [2]:
data = pd.read_csv(r"/Users/maximilianverwiebe/codingprojects/ml-from-scratch/datasets/diabetes_dataset.csv")


In [3]:
from mlfromsc.algorithms.random_forest import RandomForestClassifier
from mlfromsc import TrainTestSplit

In [4]:
y = data.copy()["Outcome"]
X = data.drop("Outcome", axis=1)

y = data["Outcome"].values
X = data.drop("Outcome", axis=1).values

train_test_split = TrainTestSplit()
X_train, X_test, y_train, y_test = train_test_split.fit(X, y, test_ratio=0.2)

In [5]:
rf = RandomForestClassifier(n_trees=50, max_depth=10)
rf.fit(X_train, y_train)

In [6]:
y_pred = rf.predict(X_test)

accuracy = np.mean(y_pred == y_test)
print(f"Accuracy: {accuracy:.2f}")

[[1 0 0 ... 1 0 0]
 [1 0 0 ... 1 1 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 1 1 ... 1 0 1]
 [1 0 0 ... 1 0 1]
 [0 0 0 ... 1 0 0]]
Accuracy: 0.68
